### ISSUE TITLE
您好，请问这个工作的源代码大概会什么时候开源呢？

### ISSUE THREAD

**Issue by Mahiro2211** [LMMMEng/TransXNet#1]

**Comment by LMMMEng** [comment]
感谢关注！代码在发布前需要一段时间进行批准和审核，一旦发布，我会立刻在此处回复您，请保持关注。
Thank you for your interest. It will take some time for the code to be reviewed and approved before release. Once it is released, I will immediately reply to you on this issue. Please keep your attention.

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月03日 11:50 |
| 收件人 | LMMMEng/TransXNet ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [LMMMEng/TransXNet] 您好，请问这个工作的源代码大概会什么时候开源呢？ (Issue #1) |

**Comment by Mahiro2211** [comment]
非常感谢🙏

**Comment by YEKAI-2022** [comment]
您好，这个源码大概什么时候发布呀！

**Comment by LMMMEng** [comment]
您好，如上述回答，代码还需要一段时间来审核，我们会尽快发布代码并回复您的，请保持关注。

**Comment by kwanking** [comment]
> 您好，如上述回答，代码还需要一段时间来审核，我们会尽快发布代码并回复您的，请保持关注。

是否可以先行公布下网络代码，或者是基本的模块，如 D-Mixer，OSRA和IDConv？

**Comment by YEKAI-2022** [comment]
> 您好，如上述回答，代码还需要一段时间来审核，我们会尽快发布代码并回复您的，请保持关注。好的，
好的，谢谢！

**Comment by LMMMEng** [comment]
您好，感谢关注！
代码，预训练模型 以及训练日志等我们会统一且尽快发布的，请保持关注哈

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月09日 09:37 |
| 收件人 | LMMMEng/TransXNet ***@***.***> |
| 抄送人 | Meng ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [LMMMEng/TransXNet] 您好，请问这个工作的源代码大概会什么时候开源呢？ (Issue #1) |

您好，如上述回答，代码还需要一段时间来审核，我们会尽快发布代码并回复您的，请保持关注。

是否可以先行公布下网络代码，或者是基本的模块，如 D-Mixer，OSRA和IDConv？

**Comment by 20201122** [comment]
您好，这个源码什么时候发布呀！很期待！

**Comment by Mahiro2211** [comment]
> 您好，这个源码什么时候发布呀！很期待！

您好，如作者所说，他会统一且尽快发布的，我们再等等吧

**Comment by LMMMEng** [comment]
代码已上传，感谢大家等待～

**Comment by Mahiro2211** [comment]
感谢
