### ISSUE TITLE
作者您好 我的数据集大概1500张图片 但是跑出来的map特别低 0.0几，用mini版大概1000张的coco数据集跑出来的map也是0.0几

### ISSUE THREAD

**Issue by JL19990910** [LMMMEng/TransXNet#10]
您知道这是怎么回事吗 是因为数据集的体量太小了吗

**Comment by LMMMEng** [comment]
应该不是数据集太小的问题。
请问你有尝试过其他模型使用你的config和数据集时候的效果吗？例如resnet

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月29日 18:09 |
| 收件人 | LMMMEng/TransXNet ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [LMMMEng/TransXNet] 作者您好 我的数据集大概1500张图片 但是跑出来的map特别低 0.0几，用mini版大概1000张的coco数据集跑出来的map也是0.0几 (Issue #10) |

您知道这是怎么回事吗 是因为数据集的体量太小了吗
