### ISSUE TITLE
What is the mmseg version？

### ISSUE THREAD

**Issue by SegmGod** [LMMMEng/TransXNet#14]
您好，请问一下您的mmseg的版本是多少呀，因为在导入预训练模型的时候提示没有安装mmseg，但是安装了以后不知道为什么导不了from mmseg.models.builder import build_backbone as seg_BACKBONES这个，麻烦您有空解答一下谢谢

**Comment by LMMMEng** [comment]
Hi, 以下是我的主要环境
```
# Environments:
cuda==11.3
python==3.8.15
# Packages:
mmcv==1.7.1
timm==0.6.12
torch==1.12.1
torchvision==0.13.1
mmsegmentation==0.30.0
```
