### ISSUE TITLE
how to obtain the relevant code？

### ISSUE THREAD

**Issue by SanmAIGO** [LMMMEng/TransXNet#3]

**Comment by SanmAIGO** [comment]
My email is sanm_li@163.com

**Comment by LMMMEng** [comment]
Thank you for your interest. We plan to release the code by the end of next week, so stay tuned.

**Comment by SanmAIGO** [comment]
> Thank you for your interest. We plan to release the code by the end of next week, so stay tuned.
Oh, That's so good! Looking forward to your code.

**Comment by LMMMEng** [comment]
Code was released, give it a try.
