### ISSUE TITLE
Expecting the author to open source

### ISSUE THREAD

**Issue by dsj0507** [LMMMEng/TransXNet#4]
May I ask when the code can be open source? Although I am not in this direction, I came across this paper by chance and felt that it was very useful for my direction. I look forward to the author's open source work.

**Comment by LMMMEng** [comment]
Thank you for your interest. We plan to release the code by the end of next week, so stay tuned.

**Comment by LMMMEng** [comment]
Code was released, give it a try.

**Comment by dsj0507** [comment]
Wow, thank you, author.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LMMMEng/TransXNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月19日(星期天) 晚上6:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LMMMEng/TransXNet] Expecting the author to open source (Issue #4)





 
Code was released, give it a try.
