### ISSUE TITLE
I have reproduced the modules in your paper and look forward to your update.

### ISSUE THREAD

**Issue by Jacky-Android** [LMMMEng/TransXNet#5]
https://github.com/Jacky-Android/TransXNet_recurrent

**Comment by LMMMEng** [comment]
Hi, thank you for your attention. I will try my best to release the source code and pre-trained model by the end of next week, then please compare the differences :)

**Comment by Jacky-Android** [comment]
Really looking forward to your updates! ! ! 😁😁😁

**Comment by LMMMEng** [comment]
Code was released, give it a try.

**Comment by Jacky-Android** [comment]
Your code gave me a lot of inspiration, thank you very much! ! !

**Comment by LMMMEng** [comment]
Thank you, kindly let me know if you have any further questions.

---- Replied Message ----
| From | ***@***.***> |
| Date | 11/19/2023 19:39 |
| To | LMMMEng/TransXNet ***@***.***> |
| Cc | Meng ***@***.***>,
State ***@***.***> |
| Subject | Re: [LMMMEng/TransXNet] I have reproduced the modules in your paper and look forward to your update. (Issue #5) |

Your code gave me a lot of inspiration, thank you very much! ! !
