### ISSUE TITLE
Questions about using TransXNet

### ISSUE THREAD

**Issue by GiaoBruce** [LMMMEng/TransXNet#6]
Hi Lou,

       Thanks for your marvelous work TransXNet!
       Recently I am trying to use TransXNet as the encoder to do some dense prediction tasks, I simply do
 
       **model = TransXNet() or model = transxnet_t()** 

       Then it goes like this

       **TypeError: GELU: __init__() got an unexpected keyword argument 'inplace'**
       
       I am wondering whether this error is related to the version of mmcv.
       Could you tell me how to correctly use TransXNet or kindly provide the requirements.txt ?
       Thanks for your generous reply. :)

**Comment by LMMMEng** [comment]
Hi, thanks for your attention, please change the version of mmcv to 1.7.1 and try again.

---- Replied Message ----
| From | ***@***.***> |
| Date | 11/22/2023 09:36 |
| To | LMMMEng/TransXNet ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [LMMMEng/TransXNet] Questions about using TransXNet (Issue #6) |

Hi Lou,

   Thanks for your marvelous work TransXNet!
   Recently I am trying to use TransXNet as the encoder to do some dense prediction tasks, I simply do

   **model = TransXNet() or model = transxnet_t()** 

   Then it goes like this

   **TypeError: GELU: __init__() got an unexpected keyword argument 'inplace'**
   
   I am wondering whether this error is related to the version of mmcv.
   Could you tell me how to correctly use TransXNet or kindly provide the requirements.txt ?
   Thanks for your generous reply. :)

**Comment by GiaoBruce** [comment]
Hi, sorry for the late response, I have already change the mmcv version from the 1.4.3 to 1.7.1, the problem has been solved.
Thanks! :)
