### ISSUE TITLE
如果使用自建数据集进行目标检测的话 需要把数据集弄成什么格式才可以运行成功呢?

### ISSUE THREAD

**Issue by JL19990910** [LMMMEng/TransXNet#9]
需要弄成coco2017的形式吗？
VOC形式的数据集可以嘛（目标检测）

**Comment by LMMMEng** [comment]
应该是没问题的，因为我使用的框架是mmdet，使用mmdet支持的格式即可

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月27日 17:05 |
| 收件人 | LMMMEng/TransXNet ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [LMMMEng/TransXNet] 如果使用自建数据集进行目标检测的话 需要把数据集弄成什么格式才可以运行成功呢? (Issue #9) |

需要弄成coco2017的形式吗？
VOC形式的数据集可以嘛（目标检测）
